name: equinasium
favicon: null
layout_spectrum: 0.6827766797505319
typography_spectrum: 0.44905518856830895
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.5756310385186225
  lightness: 0.5982715401332825
  saturation: 0.90518928039819
  rhythmicContrast: 0.5939685667399317
purpose: []
